# Generated by Django 3.1.1 on 2020-09-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200915_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalrole',
            name='pwd',
        ),
        migrations.AddField(
            model_name='institutionalrole',
            name='pwds',
            field=models.ManyToManyField(related_name='pwd_roles', to='users.Subject'),
        ),
        migrations.RemoveField(
            model_name='institutionalrole',
            name='subject',
        ),
        migrations.AddField(
            model_name='institutionalrole',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_roles', to='users.subject'),
            preserve_default=False,
        ),
    ]
