# Generated by Django 3.1.1 on 2020-09-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('users', '0003_auto_20200915_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalrole',
            name='pwds',
            field=models.ManyToManyField(related_name='i_roles', to='dictionaries.Pwd'),
        ),
        migrations.AlterField(
            model_name='institutionalrole',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_roles', to='users.subject'),
        ),
    ]
