# Generated by Django 3.1.1 on 2020-09-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('users', '0004_auto_20200915_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalrole',
            name='pwds',
        ),
        migrations.AddField(
            model_name='institutionalrole',
            name='pwd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='i_roles', to='dictionaries.pwd'),
            preserve_default=False,
        ),
    ]
