# Generated by Django 3.1.1 on 2020-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200917_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalrole',
            name='subject_role_pwd_id',
            field=models.CharField(default='9999', max_length=10),
        ),
    ]
