# Generated by Django 3.1.1 on 2022-01-21 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200917_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cstuser',
            name='created_by',
            field=models.CharField(default='System', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cstuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cstuser',
            name='modified_by',
            field=models.CharField(default='System', max_length=200),
            preserve_default=False,
        ),
    ]
