# Generated by Django 3.1.1 on 2022-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220121_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cstuser',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='cstuser',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='cstuser',
            old_name='modified_at',
            new_name='modifiedAt',
        ),
        migrations.RenameField(
            model_name='cstuser',
            old_name='modified_by',
            new_name='modifiedBy',
        ),
    ]
