# Generated by Django 3.1.1 on 2022-01-21 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionary',
            name='created_by',
            field=models.CharField(default='System', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionary',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='modified_by',
            field=models.CharField(default='System', max_length=200),
            preserve_default=False,
        ),
    ]
