# Generated by Django 3.1.1 on 2022-01-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0002_auto_20220121_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_by', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('valuesAsJSON', models.JSONField()),
                ('displayValue', models.CharField(max_length=2000, null=True)),
                ('dictionaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='slowniki.dictionary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryFieldSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_by', models.CharField(max_length=200)),
                ('order', models.SmallIntegerField()),
                ('name', models.CharField(max_length=2000)),
                ('type', models.SmallIntegerField(default=1)),
                ('isReference', models.BooleanField()),
                ('isUnique', models.BooleanField(default=False)),
                ('uniqueGroupNumber', models.SmallIntegerField(default=None, null=True)),
                ('default_value', models.CharField(default=None, max_length=2000, null=True)),
                ('isOptional', models.BooleanField(default=False)),
                ('ReferencedDict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencing_fields', to='slowniki.dictionary')),
                ('dictionaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_specs', to='slowniki.dictionary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_by', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=2000)),
                ('value', models.CharField(max_length=2000)),
                ('type', models.SmallIntegerField(default=1)),
                ('isUnique', models.BooleanField()),
                ('dictionaryEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='slowniki.dictionaryentry')),
                ('referencedValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='slowniki.dictionaryvalues')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
