# Generated by Django 3.1.1 on 2020-09-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('POPC', 'Program Operacyjny Polska Cyfrowa'), ('POIR', 'Program Operacyjny Inteligentny Rozwój'), ('KPOD', 'Krajowy Program Odbudowy'), ('FSTR', 'Fundusz Sprawiedliwej Transformacji')], max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('number', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['programme', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('vat_number', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('number', models.SmallIntegerField()),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='dictionaries.axis')),
            ],
            options={
                'ordering': ['axis', 'number'],
            },
        ),
    ]
