# Generated by Django 3.1.1 on 2020-09-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('pwd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionaries.pwd')),
                ('name', models.CharField(max_length=500)),
                ('number', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['prog', 'number'],
            },
            bases=('dictionaries.pwd',),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('pwd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionaries.pwd')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['code'],
            },
            bases=('dictionaries.pwd',),
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('pwd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionaries.pwd')),
                ('name', models.CharField(max_length=500)),
                ('number', models.SmallIntegerField()),
                ('ax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='dictionaries.axis')),
            ],
            options={
                'ordering': ['ax', 'number'],
            },
            bases=('dictionaries.pwd',),
        ),
        migrations.AddField(
            model_name='axis',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='dictionaries.programme'),
        ),
    ]
