# Generated by Django 3.1.1 on 2020-09-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_axis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axis',
            options={'ordering': ['programme', 'number']},
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('number', models.SmallIntegerField()),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='dictionaries.axis')),
            ],
            options={
                'ordering': ['axis', 'number'],
            },
        ),
    ]
